### ISSUE TITLE
Attempt to run redis if redis is not already running. Attempt reconnection

### ISSUE THREAD

**Issue by AlexFrazer** [ndugger/blackbeard#3]
I can put in a pull request if need be. Here is the trace.

```
dist :: (master*) » node app.js                                                     ~/Code/tour/dist
Charting course (running setup)...
Shivering me timbers (starting server)...
|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|
|  Blackbeard is now sailing on port 5000  |
|__________________________________________|


events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
```

Starting up redis seemed to immediately fix it though

**Comment by ndugger** [comment]
I'll look at this tomorrow; I'm under the weather today.
